
fields:

    blocks_replace_blog_editor:
        tab: hounddd.blocksforblog::lang.settings.tabs.blocks
        label: hounddd.blocksforblog::lang.settings.replace_editor
        span: full
        type: switch
        default: false
        permissions: hounddd.blocksforblog.access_settings

    allowed_blocks:
        tab: hounddd.blocksforblog::lang.settings.tabs.blocks
        label: hounddd.blocksforblog::lang.settings.allowed_blocks
        span: left
        type: taglist
        options: true
        customTags: false
        useKey: true
        permissions: hounddd.blocksforblog.access_settings
        trigger:
            action: show
            field: blocks_replace_blog_editor
            condition: checked

    allowed_tags:
        tab: hounddd.blocksforblog::lang.settings.tabs.blocks
        label: hounddd.blocksforblog::lang.settings.allowed_tags
        span: right
        type: taglist
        options: true
        customTags: false
        permissions: hounddd.blocksforblog.access_settings
        trigger:
            action: show
            field: blocks_replace_blog_editor
            condition: checked

    ignored_blocks:
        tab: hounddd.blocksforblog::lang.settings.tabs.blocks
        label: hounddd.blocksforblog::lang.settings.ignored_blocks
        span: left
        type: taglist
        options: true
        customTags: false
        useKey: true
        permissions: hounddd.blocksforblog.access_settings
        trigger:
            action: show
            field: blocks_replace_blog_editor
            condition: checked

    ignored_tags:
        tab: hounddd.blocksforblog::lang.settings.tabs.blocks
        label: hounddd.blocksforblog::lang.settings.ignored_tags
        span: right
        type: taglist
        options: true
        customTags: false
        permissions: hounddd.blocksforblog.access_settings
        trigger:
            action: show
            field: blocks_replace_blog_editor
            condition: checked

    _control:
        tab: hounddd.blocksforblog::lang.settings.tabs.blocks
        span: full
        type: partial
        path: $/hounddd/blocksforblog/partials/_control
        dependsOn:
          - allowed_blocks
          - allowed_tags
          - ignored_blocks
          - ignored_tags
        trigger:
            action: show
            field: blocks_replace_blog_editor
            condition: checked

